{"frames":[{"func":"(function (x, ...) \nUseMethod(\"print\"))(x)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"print.data.table(x)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"overridePrint(o$x, o$options, o$className, o$nRow, o$nCol)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"save(x, options, file = output)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"gzfile(file, \"wb\")","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"錯誤發生在 gzfile(file, \"wb\")：無法開啟連接\n"}